### ISSUE TITLE
avoid double feed in areas near grid district boundary

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#33]
Some load areas are cut by grid district borders, both got peak loads more than the min. peak load threshold. Therefore each of them is fed by a different MV grid - this results in overestimation of line length.

Example:
![mv_grid_double_feed](https://cloud.githubusercontent.com/assets/15910173/16109374/d10cbb66-33a8-11e6-93ed-8c46c84d533e.png)

**Comment by nesnoj** [comment]
Reason was a bug in load area SQL script.
@gplssm, please recalculate peak loads.

**Comment by gplssm** [comment]
I would like to, but I can't because materialized views depend on the table and I can't delete it. What's the plan?

**Comment by nesnoj** [comment]
Make @ludee set the correct permissions :)

**Comment by gplssm** [comment]
Done!

**Comment by nesnoj** [comment]
Addition:
Peak loads are correct right now - some of the regions now got peak loads smaller than threshold, hence less regions are double fed, but problem still existent. It is caused by the grid district method ("cut and forget").
We have to discuss how we deal with this bug - input: In reality, there are interconnections between different MV grids. The present bug doesn't connect the MV grids but leads to longer lines that could kind of represent the real "length-overhead" of the lines. But we actually can't prove it..

**Comment by gplssm** [comment]
After _data processing_ was revised, check if this issue is still present
